if(WIN32)
    set(_temp "$ENV{TEMP}")
elseif(DEFINED ENV{TMPDIR})
    set(_temp "$ENV{TMPDIR}")
else()
    set(_temp "/tmp")
endif()
string(RANDOM LENGTH 24 ALPHABET 0123456789abcdef _nonce)
set(_work "${_temp}/rh_cli_${_nonce}")
file(MAKE_DIRECTORY "${_work}")
file(WRITE "${_work}/old" "old bytes")
file(WRITE "${_work}/new" "new bytes")
file(WRITE "${_work}/bad" "bad delta")

function(check_status expected)
    execute_process(COMMAND "${RH_CLI}" ${ARGN} RESULT_VARIABLE actual OUTPUT_QUIET ERROR_QUIET)
    if(NOT actual STREQUAL "${expected}")
        file(REMOVE_RECURSE "${_work}")
        message(FATAL_ERROR "${ARGN}: expected status ${expected}, got ${actual}")
    endif()
endfunction()

check_status(2 create "${_work}/missing" "${_work}/new" "${_work}/delta")
check_status(2 create "${_work}/old" "${_work}" "${_work}/delta")
check_status(2 view "${_work}/missing")
check_status(2 apply "${_work}/missing" "${_work}/bad" "${_work}/out")
check_status(1 view "${_work}/bad")
check_status(1 apply "${_work}/old" "${_work}/bad" "${_work}/out")
check_status(0 create "${_work}/old" "${_work}/new" "${_work}/delta")
check_status(0 view "${_work}/delta")
check_status(0 apply "${_work}/old" "${_work}/delta" "${_work}/out")
check_status(1 apply --max-output 8 "${_work}/old" "${_work}/delta" "${_work}/out")
check_status(1 apply --max-output 12Q "${_work}/old" "${_work}/delta" "${_work}/out")
check_status(1 apply --max-output 99999999999999999999 "${_work}/old" "${_work}/delta" "${_work}/out")
check_status(0 apply --max-output 9 "${_work}/old" "${_work}/delta" "${_work}/out")
check_status(0 apply --max-output 1k "${_work}/old" "${_work}/delta" "${_work}/out")
file(READ "${_work}/out" rebuilt)
file(REMOVE_RECURSE "${_work}")
if(NOT rebuilt STREQUAL "new bytes")
    message(FATAL_ERROR "CLI round trip produced incorrect bytes")
endif()
